[Web-37] - signin
WhiskMedia/whisk-media pull request #1
Opened 2023-05-02 12:48 UTC by arsalan96

- Make a common folder for generic components and create a generic button component

- UI of sign in page is completed
- Inline styling fixed

2023-05-02 13:13 UTC, UmairZahid490 requested changes

2023-05-02 13:13 UTC, UmairZahid490 commented on src/pages/login.tsx
> +import { GenericButton } from '@components/common/Button';
create an index.ts file to export the components as done in other folders

2023-05-02 13:43 UTC, arsalan96 commented on src/pages/login.tsx
> +	signInContainer2: {
Done

2023-05-02 13:44 UTC, arsalan96 commented on src/pages/login.tsx
> +						<Grid sx={classes.leftLoginBackground} item xs={12}></Grid>
Done

2023-05-02 13:44 UTC, arsalan96 commented on src/pages/login.tsx
> +						<img src={whiskLogo.src} width='100%' height='100%' />
Done

2023-05-03 08:28 UTC, UmairZahid490 approved these changes
Approving

2023-05-03 08:29 UTC, merged